export enum LOCAL_CHAIN_IDS_ENUM {
    ERA_NODE = '0x104',
    LOCAL_SETUP = '0x10e',
}

export const LOCAL_CHAIN_IDS = [LOCAL_CHAIN_IDS_ENUM.ERA_NODE, LOCAL_CHAIN_IDS_ENUM.LOCAL_SETUP];

export const LOCAL_CHAINS_WITH_IMPERSONATION = [LOCAL_CHAIN_IDS_ENUM.ERA_NODE];